// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApp.Infrastructure.Data;

#nullable disable

namespace MoviesApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MoviesApp.Core.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Tim Robbins was born in West Covina, California, to Mary Robbins (née Bledsoe), an actress, and Gilbert Lee Robbins, a musician, folk singer, actor, and former manager of The Gaslight Cafe. Robbins studied drama at UCLA, where he graduated with honors in 1981.",
                            DateOfBirth = new DateTime(1958, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tim",
                            LastName = "Robbins"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "With an authoritative voice and calm demeanor, this ever-popular American actor has grown into one of the most respected figures in modern US cinema. Morgan was born on June 1, 1937 in Memphis, Tennessee, to Mayme Edna (Revere), a teacher, and Morgan Porterfield Freeman, a barber.",
                            DateOfBirth = new DateTime(1937, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Morgan",
                            LastName = "Freeman"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Marlon Brando is widely considered the greatest movie actor of all time, rivaled only by the more theatrically oriented Laurence Olivier in terms of esteem.",
                            DateOfBirth = new DateTime(1924, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marlon",
                            LastName = "Brando"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Alfredo James 'Al' Pacino established himself as a film actor during one of cinema's most vibrant decades, the 1970s, and has become an enduring and iconic figure in the world of American movies.",
                            DateOfBirth = new DateTime(1940, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Al",
                            LastName = "Pacino"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Christian Charles Philip Bale was born in Pembrokeshire, Wales, UK on January 30, 1974, to English parents Jennifer 'Jenny' (James) and David Bale.",
                            DateOfBirth = new DateTime(1974, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christian",
                            LastName = "Bale"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "When hunky, twenty-year-old heart-throb Heath Ledger first came to the attention of the public in 1999, it was all too easy to tag him as a 'pretty boy' and an actor of little depth.",
                            DateOfBirth = new DateTime(1979, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Heath",
                            LastName = "Ledger"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Liam Neeson was born on June 7, 1952 in Ballymena, Northern Ireland, to Katherine (Brown), a cook, and Bernard Neeson, a school caretaker.",
                            DateOfBirth = new DateTime(1952, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liam",
                            LastName = "Neeson"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Ben Kingsley was born Krishna Bhanji on December 31, 1943 in Scarborough, Yorkshire, England. His father, Rahimtulla Harji Bhanji, was a Kenyan-born medical doctor, of Gujarati Indian descent, and his mother, Anna Lyna Mary (Goodman), was an English actress.",
                            DateOfBirth = new DateTime(1943, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ben",
                            LastName = "Kingsley"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Elijah Wood is an American actor best known for portraying Frodo Baggins in Peter Jackson's blockbuster Lord of the Rings film trilogy.",
                            DateOfBirth = new DateTime(1981, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elijah",
                            LastName = "Wood"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Widely regarded as one of greatest stage and screen actors both in his native Great Britain and internationally, twice nominated for the Oscar and recipient of every major theatrical award in the UK and US, Ian Murray McKellen was born on May 25, 1939 in Burnley, Lancashire, England, to Margery Lois (Sutcliffe) and Denis Murray McKellen, a civil engineer and lay preacher.",
                            DateOfBirth = new DateTime(1939, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ian",
                            LastName = "McKellen"
                        });
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption",
                            Writers = "Stephen King (short story \"Rita Hayworth and Shawshank Redemption\"), Frank Darabont (screenplay)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime, Drama",
                            Rating = 9.1999999999999993,
                            ReleaseYear = 1972,
                            Title = "The Godfather",
                            Writers = "Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "When the menace known as The Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Director = "Christopher Nolan",
                            Genre = "Action, Crime, Drama",
                            Rating = 9.0,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight",
                            Writers = "Jonathan Nolan (screenplay), Christopher Nolan (screenplay)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Director = "Steven Spielberg",
                            Genre = "Biography, Drama, History",
                            Rating = 8.9000000000000004,
                            ReleaseYear = 1993,
                            Title = "Schindler's List",
                            Writers = "Thomas Keneally (book), Steven Zaillian (screenplay)"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Director = "Peter Jackson",
                            Genre = "Action, Adventure, Drama",
                            Rating = 8.9000000000000004,
                            ReleaseYear = 2003,
                            Title = "The Lord of the Rings: The Return of the King",
                            Writers = "J.R.R. Tolkien (novel), Fran Walsh (screenplay)"
                        });
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.MovieActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 3,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 4,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 5,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 6,
                            ActorId = 6,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 7,
                            ActorId = 7,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 8,
                            ActorId = 8,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 9,
                            ActorId = 9,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 10,
                            ActorId = 10,
                            MovieId = 5
                        });
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.MovieRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieRatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            RatedAt = new DateTime(1932, 6, 29, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5890),
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            RatedAt = new DateTime(2033, 2, 23, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5940),
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            RatedAt = new DateTime(1964, 9, 1, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5950),
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            RatedAt = new DateTime(2123, 7, 25, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5950),
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 2,
                            RatedAt = new DateTime(2022, 5, 3, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5960),
                            Rating = 9.5
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            RatedAt = new DateTime(2037, 5, 17, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5960),
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 2,
                            RatedAt = new DateTime(1979, 2, 6, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5960),
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 2,
                            RatedAt = new DateTime(2039, 11, 16, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5970),
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 3,
                            RatedAt = new DateTime(1934, 7, 5, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5970),
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 3,
                            RatedAt = new DateTime(2028, 3, 5, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5980),
                            Rating = 9.5
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 3,
                            RatedAt = new DateTime(2002, 12, 8, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5980),
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 3,
                            RatedAt = new DateTime(2081, 9, 12, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5990),
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 3,
                            RatedAt = new DateTime(2071, 6, 13, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5990),
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 3,
                            RatedAt = new DateTime(2074, 10, 22, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(5990),
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 4,
                            RatedAt = new DateTime(2073, 1, 20, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6000),
                            Rating = 9.5
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 4,
                            RatedAt = new DateTime(2062, 10, 9, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6000),
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 4,
                            RatedAt = new DateTime(1997, 3, 18, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6010),
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 4,
                            RatedAt = new DateTime(2039, 1, 8, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6010),
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 4,
                            RatedAt = new DateTime(2122, 12, 4, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6020),
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 4,
                            RatedAt = new DateTime(2057, 2, 20, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6020),
                            Rating = 9.5
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 5,
                            RatedAt = new DateTime(1975, 12, 29, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6030),
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 5,
                            RatedAt = new DateTime(1929, 6, 30, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6030),
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 5,
                            RatedAt = new DateTime(1986, 1, 8, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6030),
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 5,
                            RatedAt = new DateTime(2012, 6, 11, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6040),
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 5,
                            RatedAt = new DateTime(2056, 3, 20, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6040),
                            Rating = 9.5
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 5,
                            RatedAt = new DateTime(2107, 5, 8, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6050),
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 5,
                            RatedAt = new DateTime(2041, 4, 18, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6050),
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 5,
                            RatedAt = new DateTime(2100, 3, 19, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6050),
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 5,
                            RatedAt = new DateTime(2048, 5, 2, 12, 50, 24, 213, DateTimeKind.Local).AddTicks(6060),
                            Rating = 9.3000000000000007
                        });
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.MovieActor", b =>
                {
                    b.HasOne("MoviesApp.Core.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesApp.Core.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.MovieRating", b =>
                {
                    b.HasOne("MoviesApp.Core.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("MoviesApp.Core.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");
                });
#pragma warning restore 612, 618
        }
    }
}
